### ISSUE TITLE
SweetAlertResult 항목 추가 필요

### ISSUE THREAD

**Issue by kerokim** [Jungwoo-An/SweetAlertSharp#1]
안녕하세요.

SweetAlertResult 항목이 OK와 Cancel로만 이루어져 있어서 버튼 형태가 SweetAlertButton.YesNo나 SweetAlertButton.YesNoCancel 인 경우에 대한 처리가 어렵습니다.

**Comment by Jungwoo-An** [comment]
@kerokim 첫 이슈 감사합니다. 🎉

우선 첫 설계에 Yes No 에 대한 처리를 하지 않은 이유는, Yes/No 가 Ok/Cancel 과 정확히 매칭되어 있어서였습니다. 코드의 명료함을 위해 YesNo 를 추가하는 건 의미 있을 것 같습니다. 좋아요! 👍 (~다음부터는 컨트리뷰팅을... ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ~)

**Comment by kerokim** [comment]
답변 감사합니다~

이 이슈를 등록한 계기는 SweetAlertButton.YesNoCancel 때문입니다. Yes는 OK로 대응한다고 해도 No와 Cancel을 동일하게 Cancel 하나로 대응하기에는 무리가 있었습니다. 그래서 표현할 수 있는 버튼의 종류 만큼 SweetAlertResult가 존재해야 한다고 생각했습니다.

**Comment by Jungwoo-An** [comment]
아마 YesNoCancel 은 enum 만 존재하고 실제 기능으로 작동하진 않았을 거예요. 해당 enum 은 당장/추후에도 필요 없을 거라 생각되어 제거했습니다. (YesNoCanel 을 쓰면 아마 Ok 버튼만 보였을텐데...)

관련 PR 은 #2 이고, 더 이상 논의할만한 내용이 없는 것 같아 해당 이슈는 닫겠습니다. (v1.3.0 배포됐어요!) 혹시 다른 논의 내용이 있으시면 재오픈하고 이야기 나누면 될 것 같습니다. 수고하셨습니다!
