### ISSUE TITLE
SweetAlert being weirdly displayed

### ISSUE THREAD

**Issue by Laiteux** [Jungwoo-An/SweetAlertSharp#3]
Hello,

I'm trying to use SweetAlertSharp but am encountering an issue.

This code works as intended and displays a beautiful alert:
```cs
SweetAlert.Show("Error", "Whatever");
```

However, this one (which should lead do the exact same result as the above one) doesn't work well:
```cs
new SweetAlert
{
    Caption = "Error",
    Content = "Whatever"
}.ShowDialog();
```

In fact, this is what's being displayed on my screen (the blue background is my Windows wallpaper):
![](https://laiteux.dev/wbuckm.gif)

I am using a Windows.Forms project on .NET Framework 4.7.2.

Regards,
Matt.

**Comment by Jungwoo-An** [comment]
@Laiteux Hi! First of all, thanks for your interest! ❤️

I think you want to change message content, then should set `Message` property. (see the below code)

```cs
new SweetAlert {
    Caption = "Error",
    Message = "Whatever",
}.ShowDialog();
```

Thanks!

**Comment by Laiteux** [comment]
That fixed it!

I didn't notice you were using `Message` instead of `Content` in the documentation.

Let's say that's because it was 3 AM :3

Thanks for your help and for this amazing library, even tho I think your notification woke me up haha <3

**Comment by Laiteux** [comment]
Also a quick question, do you plan on adding [InputBox](https://docs.microsoft.com/fr-fr/dotnet/api/microsoft.visualbasic.interaction.inputbox)es?

That would be a really nice feature even tho I'm not sure it matches the original project idea.

I just can't be bothered to use these ugly default ones and couldn't find any library for this purpose...
