### ISSUE TITLE
Change and customise A Button and the Alert itself

### ISSUE THREAD

**Issue by rhpo** [Jungwoo-An/SweetAlertSharp#5]
Hi, 
i think the title describes everything..
- How do i customise an alert Button (Font, BackgroundColor,BgImage, etc...)
- and the same thing with the Alert itself?

Thanks for your replies.

**Comment by Jungwoo-An** [comment]
@rhpo Yes. SweetAlertSharp can't be customizable. I have no plans.

Thanks!
